// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRWCd-dTNa0cnPLio2qskyMABC7NOi0Zg',
    appId: '1:177971684369:web:4a4495b1e787ace1e0fdb0',
    messagingSenderId: '177971684369',
    projectId: 'flutterbytes-learning-project',
    authDomain: 'flutterbytes-learning-project.firebaseapp.com',
    storageBucket: 'flutterbytes-learning-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLOlFDW6Foh8cOmyugkmzutxD8AVHMcw',
    appId: '1:177971684369:android:f3e70ce565b9249fe0fdb0',
    messagingSenderId: '177971684369',
    projectId: 'flutterbytes-learning-project',
    storageBucket: 'flutterbytes-learning-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWYR4nJveRb1WR27G06RSVsEs59yhhQE',
    appId: '1:177971684369:ios:78ae062ec40b5441e0fdb0',
    messagingSenderId: '177971684369',
    projectId: 'flutterbytes-learning-project',
    storageBucket: 'flutterbytes-learning-project.appspot.com',
    iosClientId: '177971684369-hqj52gkc87l63nle480mvbpcgj29cr48.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeWYR4nJveRb1WR27G06RSVsEs59yhhQE',
    appId: '1:177971684369:ios:78ae062ec40b5441e0fdb0',
    messagingSenderId: '177971684369',
    projectId: 'flutterbytes-learning-project',
    storageBucket: 'flutterbytes-learning-project.appspot.com',
    iosClientId: '177971684369-hqj52gkc87l63nle480mvbpcgj29cr48.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningProject',
  );
}
